### ISSUE TITLE
Spark-Retrieval/data/embed.csv is empty

### ISSUE THREAD

**Issue by Graygaoyu** [massquantity/dismember#5]
I noticed that you are still updating your code， some bugs sometimes appear.
Is there any historical version of the code that works fine?
Would you like to share it?
Thank you very much.

**Comment by massquantity** [comment]
The library is currently in developing mode and I don't keep the historical versions.
The `main` branch should be runnable. Could you describe your process and what kind of bugs you are facing?
If the training is successful, it's weird that `embed.csv` is empty.
